### ISSUE TITLE
Simplify configuration handling

### ISSUE THREAD

**Issue by o-reo** [Cosmo-Tech/Babylon#150]
Merging configuration files in only one `babylon_config.yml` file with sections

-  Move configuration only used in resource creation in working directory
 - Investigate using https://www.dynaconf.com/
 example:
```yaml 
 webapp_location: ""
 webapp_repository: ""
 webapp_repository_branch: ""
 ```

Separating taks:
- Prepare the skeleton of how a project will look like in terms of configuration files and validate it with CAT and Asset
- Investigate pros and cons of using Dynaconf to handle configuration files
- Replace require_platform and require_deploy by looking up configuration in the Environment singleton
- Change all commands to use new configuration values
  - API
  - Azure
  - PowerBI
