### ISSUE TITLE
Adx Cluster name key in platform config is not explicit

### ISSUE THREAD

**Issue by johnfolly** [Cosmo-Tech/Babylon#89]
# Adx Cluster name key in platform config is not explicit

Adx cluster name and database name key could be named: 

```yaml
# adx_cluster_name: The name of the Azure Data Explorer Cluster
adx_cluster_name: ""
# adx_database_name : the name of the database used in Azure Data Explorer
adx_database_name: ""
```
